name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    name: Pull image from DockerHub and start container
    steps:
      - name: Pull docker image
        run: sudo docker pull saikhnaa21/apelance:latest
      - name: Delete Old docker container
        run: sudo docker rm -f apelance-container || true
      - name: Run Docker Container
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          WEB3_URL: ${{secrets.WEB3_URL}}
          WEB3_API_KEY: ${{secrets.WEB3_API_KEY}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
        run: >
          sudo docker run -d
          -e MONGO_URI=$MONGO_URI
          -e JWT_SECRET=$JWT_SECRET
          -e WEB3_URL=$WEB3_URL
          -e WEB3_API_KEY=$WEB3_API_KEY
          -e SECRET_KEY=$SECRET_KEY
          -e S3_ACCESS_KEY=$S3_ACCESS_KEY
          -e S3_SECRET_KEY=$S3_SECRET_KEY
          -e S3_REGION=us-east-2
          -p 8000:3000 --name apelance-container saikhnaa21/apelance
      - name: Cleanup unused images
        run: sudo docker image prune --force